# Generated by Django 4.2.9 on 2024-01-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_quantityvariant_sizevariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariant',
            old_name='variant_name',
            new_name='color_name',
        ),
        migrations.RenameField(
            model_name='quantityvariant',
            old_name='variant_name',
            new_name='quantity_name',
        ),
        migrations.RenameField(
            model_name='sizevariant',
            old_name='variant_name',
            new_name='size_name',
        ),
    ]
