# Generated by Django 4.2.9 on 2024-01-07 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_variant_name_colorvariant_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
